const char *ERROR_STRINGS[] =
        {
//English
                "Success",
                "FILE NOT FOUND",
                "The Disc Cover is open.\n If you want to continue the game,\n please close the Disc Cover.",
                "This is not \nThe Simpsons Hit & Run\nGame Disc.  Please insert\nThe Simpsons Hit & Run\nGame Disc.",
                "Please insert \nThe Simpsons Hit & Run\n Game Disc.",
                "Please insert \nThe Simpsons Hit & Run\n Game Disc.",
                "The Game Disc could not be read.\nPlease read the\nNintendo GameCube Instruction Booklet\nfor more information.",
                "Please insert \nThe Simpsons Hit & Run\n Game Disc.",
                "Please insert \nThe Simpsons Hit & Run\n Game Disc.",
                "Please insert \nThe Simpsons Hit & Run\n Game Disc.",
                "Please insert \nThe Simpsons Hit & Run\n Game Disc.",
                "Please insert \nThe Simpsons Hit & Run\n Game Disc.",
                "Please insert \nThe Simpsons Hit & Run\n Game Disc.",
//French
                "Success",
                "FILE NOT FOUND",
                "Le couvercle est ouvert.\nPour continuer � jouer,\nveuillez fermer le couvercle.",
                "Ce n'est pas le disque\nThe Simpsons Hit & Run. Veuillez ins�rer\nle disque: The Simpsons Hit & Run.",
                "Veuillez ins�rer le disque:\nThe Simpsons Hit & Run.",
                "Veuillez ins�rer le disque:\nThe Simpsons Hit & Run.",
                "La lecture du disque a �chou�.\nVeuillez vous r�f�rer au\nmanuel d'instructions\nNINTENDO GAMECUBE\npour de plus amples informations.",
                "Veuillez ins�rer le disque:\nThe Simpsons Hit & Run.",
                "Veuillez ins�rer le disque:\nThe Simpsons Hit & Run.",
                "Veuillez ins�rer le disque:\nThe Simpsons Hit & Run.",
                "Veuillez ins�rer le disque:\nThe Simpsons Hit & Run.",
                "Veuillez ins�rer le disque:\nThe Simpsons Hit & Run.",
                "Veuillez ins�rer le disque:\nThe Simpsons Hit & Run.",
//German
                "Success",
                "FILE NOT FOUND",
                "Der Disc-Deckel ist ge�ffnet.\nBitte den Disc-Deckel schlie�en,\num mit dem Spiel fortzufahren.",
                "Es befindet sich nicht die THE SIMPSONS\nHit & Run Game Disc im Laufwerk.\nBitte legen Sie die THE SIMPSONS\nHit & Run Game Disc ein.",
                "Bitte die\nTHE SIMPSONS Hit & Run-Game Disc\neinlegen.",
                "Bitte die\nTHE SIMPSONS Hit & Run-Game Disc\neinlegen.",
                "Diese Game Disc kann nicht gelesen\nwerden.  Bitte lesen Sie die\nBedienungsanleitung,\num weitere Informationen zu erhalten.",
                "Bitte die\nTHE SIMPSONS Hit & Run-Game Disc\neinlegen.",
                "Bitte die\nTHE SIMPSONS Hit & Run-Game Disc\neinlegen.",
                "Bitte die\nTHE SIMPSONS Hit & Run-Game Disc\neinlegen.",
                "Bitte die\nTHE SIMPSONS Hit & Run-Game Disc\neinlegen.",
                "Bitte die\nTHE SIMPSONS Hit & Run-Game Disc\neinlegen.",
                "Bitte die\nTHE SIMPSONS Hit & Run-Game Disc\neinlegen.",
//Spanish
                "Success",
                "FILE NOT FOUND",
                "La tapa est� abierta.\nSi quieres seguir jugando,\ncierra la tapa.",
                "Este no es el disco de\nThe Simpsons Hit & Run. Coloca el disco de\nThe Simpsons Hit & Run.",
                "Coloca el disco de The Simpsons Hit & Run.",
                "Coloca el disco de The Simpsons Hit & Run.",
                "No se puede leer el disco.\nConsulta el manual de\ninstrucciones de NINTENDO GAMECUBE\npara obtener m�s informaci�n.",
                "Coloca el disco de The Simpsons Hit & Run.",
                "Coloca el disco de The Simpsons Hit & Run.",
                "Coloca el disco de The Simpsons Hit & Run.",
                "Coloca el disco de The Simpsons Hit & Run.",
                "Coloca el disco de The Simpsons Hit & Run.",
                "Coloca el disco de The Simpsons Hit & Run.",

                "" // dummy terminator

        };
