const char *ERROR_STRINGS[] =
        {
//English
                "Success",
                "FILE NOT FOUND",
                "The disc tray is open",
                "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
                "No disc. \nInsert The Simpsons Hit & Run disc.",
                "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
                "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
                "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
                "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
                "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
                "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
                "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
                "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
//French
                "Success",
                "FILE NOT FOUND",
                "Le compartiment � disque est ouvert.",
                "Disque incorrect.\nIns�rez le disque The Simpsons Hit & Run.",
                "Aucun disque.\nIns�rez le disque The Simpsons Hit & Run.",
                "Disque incorrect.\nIns�rez le disque The Simpsons Hit & Run.",
                "Disque incorrect.\nIns�rez le disque The Simpsons Hit & Run.",
                "Disque incorrect.\nIns�rez le disque The Simpsons Hit & Run.",
                "Disque incorrect.\nIns�rez le disque The Simpsons Hit & Run.",
                "Disque incorrect.\nIns�rez le disque The Simpsons Hit & Run.",
                "Disque incorrect.\nIns�rez le disque The Simpsons Hit & Run.",
                "Disque incorrect.\nIns�rez le disque The Simpsons Hit & Run.",
                "Disque incorrect.\nIns�rez le disque The Simpsons Hit & Run.",
//German
                "Success",
                "FILE NOT FOUND",
                "Die DVD/CD - Lade ist ge�ffnet",
                "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
                "Keine DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
                "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
                "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
                "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
                "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
                "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
                "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
                "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
                "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
//Spanish
                "Success",
                "FILE NOT FOUND",
                "La bandeja del disco est� abierta.",
                "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
                "No se ha introducido ning�n disco.\nInserta el disco de Simpsons Hit & Run.",
                "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
                "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
                "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
                "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
                "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
                "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
                "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
                "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",

                "" // dummy terminator

        };
