const char *ERROR_STRINGS[] =
        {
//English
                "Success",
                "FileNotFound",
                "ShellOpen",
                "WrongMedia",
                "There's a problem with the disc you're using. It may be dirty or damaged. Press A to continue.",
                "There's a problem with the disc you're using. It may be dirty or damaged. Press A to continue.",
                "There's a problem with the disc you're using. It may be dirty or damaged. Press A to continue.",
                "Your Xbox doesn't have enough free blocks to save games. Press A to continue without saving or B to free more blocks.",
                "Your Xbox doesn't have enough free blocks to save games. Press A to continue without saving or B to free more blocks.",
                "MediaEncodingErr",
                "MediaWrongType",
                "MediaInvalid",
                "DataCorrupt",
//French
                "NON SOUTENU",
                "NON SOUTENU",
                "NON SOUTENU",
                "NON SOUTENU",
                "�CHEC DE MAT�RIEL",
                "�CHEC DE MAT�RIEL",
                "�CHEC DE MAT�RIEL",
                "�CHEC DE MAT�RIEL",
                "HORS DE L'ESPACE",
                "NON SOUTENU",
                "NON SOUTENU",
                "NON SOUTENU",
                "NON SOUTENU",
        };
