const char *ERROR_STRINGS[] =
        {
//English
                "Success",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
                "The Disc Tray is open.\nIf you want to continue the game,\nplease close the Disc Tray.",
                "This is not \nThe Simpsons Hit & Run\nGame Disc.  Please insert\nThe Simpsons Hit & Run\nGame Disc.",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
                "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
//French
                "Success",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
                "",
                "",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
                "Le disque utilis� pr�sente une anomalie.\nIl est peut-�tre sale ou endommag�.",
//German
                "Success",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
                "",
                "",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
                "Problem bei der benutzten CD:\nCD ist verschmutzt oder besch�digt.",
//Spanish
                "Success",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",
                "",
                "",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",
                "Hay un problema con el disco que est�s usando.\nPuede estar sucio o da�ado.",

                "" // dummy terminator

        };
